lucasevero/instrument_rental

app/models/user.rb
config/routes.rb
db/migrate/20210531190423_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

User Model Created

---

Gemfile.lock
app/controllers/offers_controller.rb
app/models/offer.rb
app/views/offers/index.html.erb
config/routes.rb
db/migrate/20210531193330_create_offers.rb
db/schema.rb
test/controllers/offers_controller_test.rb
test/models/offer_test.rb

Created Offer model and controllers, with these methods: index, show, new, create

Create offer model

---

app/controllers/deals_controller.rb
app/models/deal.rb
app/models/offer.rb
app/models/user.rb
app/views/offers/index.html.erb
app/views/offers/new.html.erb
app/views/offers/show.html.erb
app/views/pages/home.html.erb
config/routes.rb
db/migrate/20210531211514_create_deals.rb
db/migrate/20210531212530_add_default_value_to_deal.rb
db/migrate/20210601171424_add_dates_to_deal.rb
db/schema.rb
db/seeds.rb
test/controllers/deals_controller_test.rb
test/models/deal_test.rb

Created Deal model, with controller and the following routes:
deals#index
deals#new
deals#create
deals#approve
deals#deny

Create model deal

---

app/models/user.rb

Now it should be possible to have one profile picture associated to users

added picture association to User model

---

app/assets/stylesheets/components/_index.scss

Fixed a bug
; missing in _index.scss

Bug in _index.scss fixed

---

app/controllers/offers_controller.rb

Instatiated a Deal instance in offers#show, so that the form to create a new deal can be placed inside an offer

added possibility to instantiate a new deal in offers#show

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb
db/migrate/20210601211918_add_firs_name_last_name_to_users.rb
db/schema.rb

Added a has_one_picture_attached relation to User
Added first_name and last_name attributes to User

addes firs_name and last_name to User

---

app/controllers/offers_controller.rb
app/views/offers/show.html.erb
config/routes.rb

Just implemented the delete in the offers controller.
For that to work, I let `resources :offers` to have all the 7 actions.
There is a bug about `before_action :authenticate_user!` which is not letting an unlogged user access the index and the show — yet to be fixed.
In the views, add the delete button must use `data: { confirm: ‘Are you sure?’ }`.

Delete offer implemented

---

app/controllers/offers_controller.rb

Fix a bug so users can see the index and show pages

Skip authenticate_user for index e show

---

app/assets/stylesheets/components/_footer.scss
app/views/shared/_footer.html.erb
config/webpacker.yml

Removed fixed attribute and added social buttons

Fix footer

---

app/controllers/offers_controller.rb
config/routes.rb

Edit update Offers

---

app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb
config/webpacker.yml

Implemented flash alerts when logging in

implemented flash alerts on top of page

---

app/controllers/offers_controller.rb

fix bug on conditional if/else on update method

update fixed with end on condition

---

app/views/offers/index.html.erb
app/views/offers/show.html.erb
app/views/shared/_flashes.html.erb

Photo in show

---

app/views/offers/index.html.erb

image sizes

---

app/views/devise/registrations/new.html.erb

Added fields for First Name and Last Name in sign up form

Devise form name inputs

---

app/assets/stylesheets/components/_search.scss
app/controllers/offers_controller.rb
app/views/offers/index.html.erb
app/views/shared/_instruments_cards.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_searchbar.html.erb

- Search bar is now an independent partial
- Added a form to the search bar
- Cards in the home page redirect to index pages for those instruments
- Added some breathing space to the Index view
- Queries are working for instrument(name), description and location

Searchbar form

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/offers_controller.rb
app/javascript/plugins/init_carousel.js
app/models/offer.rb
app/policies/application_policy.rb
app/policies/offer_policy.rb
app/views/offers/new.html.erb
app/views/offers/show.html.erb
test/policies/offer_policy_test.rb

Works on my localhost should works on yours

Pundit authorization

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/deals_controller.rb
app/controllers/users_controller.rb
app/models/offer.rb
app/views/users/manage.html.erb
config/routes.rb

Create profile page for users to manage their deals and offers

Profile page show

---

app/assets/stylesheets/application.scss
app/views/offers/show.html.erb

Fixed carousel. 
Just for the record, the problem wasn't Javascript. The problem was that I had forgotten to include a carousel-item class in each photo.

fixed carousel

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_form.scss
app/views/offers/new.html.erb

Changed the style of new offer form

improved style for new offer form

---

app/assets/stylesheets/components/_banner.scss
app/controllers/offers_controller.rb
app/views/offers/index.html.erb
app/views/shared/_instruments_cards.html.erb
db/migrate/20210603184528_add_name_to_offers.rb
db/migrate/20210603185854_add_overview_to_offers.rb
db/schema.rb
db/seeds.rb

- Migration: add name to offers
- Migration: add overview to offers
- Seed
- Index view changed to have overview and name
- Search bar now looks for offer's name and overview as well
- Added a top-border to the banner

Improving seeds

---

app/controllers/deals_controller.rb
app/policies/deal_policy.rb
test/policies/deal_policy_test.rb

Policy deals

---

app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

Buttons in log in page and in sign up page styled correctly

---

app/controllers/application_controller.rb
app/controllers/deals_controller.rb
app/views/offers/show.html.erb

Put flash alert when user books instrument

Booking alert

---

app/assets/stylesheets/components/_cards.scss
app/controllers/deals_controller.rb
app/controllers/users_controller.rb
app/views/users/manage.html.erb

Improved cards in profile page and implemented flash alerts

improved cards and added flash alerts

---

app/assets/stylesheets/components/_instruments_cards.scss
app/views/shared/_instruments_cards.html.erb

- Instruments cards aligned in a 3x2
- Names are hidden until you hover

Changes in the home page's cards

---

app/views/users/manage.html.erb

Added margins top and bottom to containers
Pluralized the 'offer' in the banner

add margins top and bottom to containers and pluralized offer

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Navbar with new buttons

---

app/views/shared/_footer.html.erb

Andre's hearth on the footer

---

app/views/offers/new.html.erb

Added Name and Overview fields to New Offer Form

added name and overview fields to new offer form

---

app/assets/stylesheets/components/_cards.scss
app/views/users/manage.html.erb

- Deal card with padding
- Deal status capitalized

Visual changes in de deal card of the profile

---

app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/components/_index.scss
app/views/devise/sessions/new.html.erb

Changed container of sign in form

changed sign in container

---

app/controllers/offers_controller.rb
app/helpers/application_helper.rb

permitted name and overview in new offer form

permitted name and overview in new offer form
